version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:8.0.32-aarch64
    container_name: mysql_sakila_db
    volumes:
      - mysql_sakila_db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: sakila
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo

volumes:
  mysql_sakila_db: